### PR TITLE
Add support for BigInt

### PR DESCRIPTION
**Pull request by JesusTheHun**
Following https://github.com/storybookjs/storybook/issues/13950, this PR add support for bigint

### CODE REVIEW

**Comment by JesusTheHun** [comment]
Tests pass locally, can you share what happened on CI ?

**Comment by shilman** [comment]
```
/home/circleci/project/src/index.ts
   64:33  warning  Unexpected unnamed function  func-names
  336:14  error    'BigInt' is not defined      no-undef
```

**Comment by JesusTheHun** [comment]
`BigInt` landed in `NodeJS 10.4.0` so we may have to add a polyfill to support earlier versions.

**Comment by JesusTheHun** [comment]
Actually I don't know how to proceed in this case. Adding a polyfill would not test the native object and therefore be irrelevant. 
But I see it's in `corejs` which you recommend in case of lack of support on the project's `README`. So.. I don't know how to move forward from here.

**Comment by phated** [comment]
I think the matrix should probably include node 12 and 14 and then you can check something like `if ('BigInt' in global) {` inside the test and add an eslint comment for that line.

**Review by swedish84CY — APPROVED** [review]
src/index.ts

**Review by gaetanmaisse — APPROVED** [review]

**Pull request merged**
