### PR TITLE
Allow eval'd results to be returned, added browserify step.

### PR DESCRIPTION
**Pull request by cawfree**
Hey, thanks a lot for this library.

I've added a couple of changes:
  - Results from serialized functions can be returned when invoked.
  - Added a [browserify](http://browserify.org/) step to enable use on the web.
  - Bumped the package version to `2.2.2`.

Thanks again!

### CODE REVIEW

**Comment by ndelangen** [comment]
I think we'd need to run browserify before publishing?

**Comment by ndelangen** [comment]
@cawfree thanks for contributing, I'm changing this lib's source to typescript, what would we need to do to get this merged as well? see #21

**Comment by cawfree** [comment]
Hey @ndelangen, thanks for getting back to me!

The `browserify` stage is an optional extra script that I found useful when deploying this to a CDN as opposed to importing directly into node.

The only _real_ change is that when `eval` of a serialized function is performed, it would be useful if it is `return`ed by the function call. At the moment, the wrapper function just returns `undefined`.

Wish I could just fix up the Pull Request, but I haven't learnt TypeScript yet. Sorry about that.

**Comment by ndelangen** [comment]
You can contribute without writing any types at all. It's fine.

I can assist and add some types.

**Comment by cawfree** [comment]
Looks like this functionality has since [been introduced](https://github.com/storybookjs/telejson/blob/bd61a3fbdeca7049798a1920dd316642e4a643cc/src/index.ts#L287). Thanks!

**Pull request closed without merging**
